databases:
  - name: imu_racing_game_db
    plan: free
    databaseName: imu_racing_game
    user: imu_racing_game

services:
  - type: web
    plan: free
    name: imu_racing_game
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "pipenv run daphne -b 0.0.0.0 imu_racing_game.asgi:application"
    envVars:
      - key: USE_POSTGRES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: imu_racing_game_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4